# Generated by Django 3.2.19 on 2023-05-26 10:43

from django.db import migrations, models
import lti_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_client_id',
            field=models.CharField(blank=True, help_text='Client ID used by LTI tool', max_length=255),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_private_key',
            field=models.TextField(blank=True, help_text="Platform's generated Private key. Keep this value secret.", validators=[lti_store.models.validate_private_key]),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_private_key_id',
            field=models.CharField(blank=True, help_text="Platform's generated Private key ID", max_length=255),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_public_jwk',
            field=models.TextField(blank=True, help_text="Platform's generated JWK keyset."),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_tool_keyset_url',
            field=models.URLField(blank=True, help_text="This is the LTI Tool's JWK (JSON Web Key)\n        Keyset (JWKS) URL. This should be provided by the LTI\n        Tool. One of either lti_1p3_tool_public_key or\n        lti_1p3_tool_keyset_url must not be blank.", max_length=255, verbose_name='LTI 1.3 Tool Keyset URL'),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_tool_public_key',
            field=models.TextField(blank=True, help_text="This is the LTI Tool's public key.\n        This should be provided by the LTI Tool.\n        One of either lti_1p3_tool_public_key or\n        lti_1p3_tool_keyset_url must not be blank.", verbose_name='LTI 1.3 Tool Public Key'),
        ),
        migrations.AlterField(
            model_name='externallticonfiguration',
            name='version',
            field=models.CharField(choices=[('lti_1p1', 'LTI 1.1'), ('lti_1p3', 'LTI 1.3')], default='lti_1p1', max_length=10),
        ),
    ]
