# Generated by Django 3.2.19 on 2023-07-07 16:49

from django.db import migrations, models
import lti_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_store', '0002_auto_20230526_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_deployment_id',
            field=models.CharField(blank=True, help_text='Deployment ID used by LTI tool', max_length=255, verbose_name='LTI 1.3 Deployment ID'),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_launch_url',
            field=models.CharField(blank=True, help_text='This is the LTI launch URL, otherwise known as the target_link_uri.\n        It represents the LTI resource to launch to or load in the second leg of the launch flow,\n        when the resource is actually launched or loaded.', max_length=255, verbose_name='LTI 1.3 Launch URL'),
        ),
        migrations.AddField(
            model_name='externallticonfiguration',
            name='lti_1p3_oidc_url',
            field=models.CharField(blank=True, help_text='This is the OIDC third-party initiated login endpoint URL in the LTI 1.3 flow,\n        which should be provided by the LTI Tool.', max_length=255, verbose_name='LTI 1.3 OIDC URL'),
        ),
        migrations.AlterField(
            model_name='externallticonfiguration',
            name='lti_1p3_client_id',
            field=models.CharField(blank=True, help_text='Client ID used by LTI tool', max_length=255, verbose_name='LTI 1.3 Client ID'),
        ),
        migrations.AlterField(
            model_name='externallticonfiguration',
            name='lti_1p3_private_key',
            field=models.TextField(blank=True, help_text="Platform's generated Private key. Keep this value secret.", validators=[lti_store.models.validate_private_key], verbose_name='LTI 1.3 Private Key'),
        ),
        migrations.AlterField(
            model_name='externallticonfiguration',
            name='lti_1p3_private_key_id',
            field=models.CharField(blank=True, help_text="Platform's generated Private key ID", max_length=255, verbose_name='LTI 1.3 Private Key ID'),
        ),
        migrations.AlterField(
            model_name='externallticonfiguration',
            name='lti_1p3_public_jwk',
            field=models.TextField(blank=True, help_text="Platform's generated JWK keyset.", verbose_name='LTI 1.3 Public JWK'),
        ),
    ]
